# Generated by Django 5.0.6 on 2024-05-27 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerinfo',
            name='phone_number',
            field=models.CharField(help_text='Please Enter contact number, without +91', max_length=17),
        ),
        migrations.AlterField(
            model_name='sellerinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sellerinfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
