# Generated by Django 5.0.6 on 2024-05-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerinfo',
            name='phone_number',
            field=models.CharField(help_text='Please enter the phone number, without +91', max_length=17),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone_number',
            field=models.CharField(help_text='Please enter the phone number, without +91', max_length=17),
        ),
    ]
