# Generated by Django 5.0.6 on 2024-05-28 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_alter_sellerinfo_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='phone_number',
        ),
    ]
