# Generated by Django 5.0.6 on 2024-05-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0005_remove_userinfo_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='phone_number',
            field=models.CharField(default='', help_text='Please enter the phone number, without +91', max_length=17),
        ),
        migrations.AlterField(
            model_name='sellerinfo',
            name='phone_number',
            field=models.CharField(default='', help_text='Please enter the phone number, without +91', max_length=17),
        ),
    ]
