# Generated by Django 5.0.6 on 2024-07-01 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0007_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
