# Generated by Django 5.0.6 on 2024-07-06 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0009_query'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Query',
        ),
    ]
