# Generated by Django 4.1.4 on 2022-12-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='success_status',
            field=models.CharField(choices=[('1', 'UPI'), ('2', 'CARD'), ('3', 'TRANSFER'), ('4', 'OTHER')], max_length=255),
        ),
    ]
