# Generated by Django 4.1.4 on 2022-12-14 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_payment_success_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=36, verbose_name='Payment ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_order_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=40, verbose_name='Order ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='signature_id',
            field=models.CharField(default=1, max_length=128, verbose_name='Signature ID'),
            preserve_default=False,
        ),
    ]
