# Generated by Django 4.1.4 on 2023-01-03 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='end_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
