# Generated by Django 5.0.6 on 2024-05-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_category_catalogue_alter_product_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='opening_bid',
            field=models.IntegerField(default=0),
        ),
    ]
