# Generated by Django 5.0.6 on 2024-05-16 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_bid_opening_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='opening_bid',
        ),
    ]
