# Generated by Django 5.0.6 on 2024-05-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_bid_opening_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='opening_bid',
            field=models.IntegerField(default=0),
        ),
    ]
