# Generated by Django 5.0.6 on 2024-05-22 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_product_opening_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_qty',
        ),
    ]
