# Generated by Django 5.0.6 on 2024-05-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_rename_product_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='product_qty',
            field=models.IntegerField(default=0),
        ),
    ]
