# Generated by Django 5.0.6 on 2024-05-25 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_artwork_product_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='product_name',
            new_name='Name',
        ),
    ]
