# Generated by Django 5.0.6 on 2024-05-25 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_rename_product_name_artwork_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='order_price',
        ),
    ]
