# Generated by Django 5.0.6 on 2024-05-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_remove_ordermodel_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='order_price',
            field=models.FloatField(default=0),
        ),
    ]
