# Generated by Django 5.0.6 on 2024-05-25 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_ordermodel_order_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='Name',
            new_name='product_name',
        ),
    ]
