# Generated by Django 5.0.6 on 2024-05-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_rename_is_read_notification_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
