# Generated by Django 5.0.6 on 2024-06-02 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_rename_length_cm_artwork_length_in_centimeters_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='length_in_foot',
            new_name='foot',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='width_in_foot',
            new_name='inches',
        ),
    ]
