# Generated by Django 5.0.6 on 2024-06-02 07:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_rename_length_in_foot_artwork_foot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='dimension_unit',
            field=models.CharField(choices=[('cm', 'Centimeters'), ('ft', 'Feet')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
