# Generated by Django 5.0.6 on 2024-06-02 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_artwork_dimension_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='dimension_unit',
        ),
    ]
