# Generated by Django 5.0.6 on 2024-06-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_remove_artwork_dimension_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='foot',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='inches',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
