# Generated by Django 5.0.6 on 2024-06-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alter_artwork_foot_alter_artwork_inches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='foot',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='inches',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
