# Generated by Django 5.0.6 on 2024-06-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_artwork_dimension_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='PENDING', max_length=254, verbose_name='Payment Status'),
        ),
    ]
