# Generated by Django 5.0.6 on 2024-06-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_artwork_last_bid_artwork_total_bids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='last_bid',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='total_bids',
        ),
    ]
