# Generated by Django 5.0.6 on 2024-06-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_remove_artwork_last_bid_remove_artwork_total_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
