# Generated by Django 5.0.6 on 2024-06-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_artwork_is_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='opening_bid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='product_price',
            field=models.FloatField(default=0),
        ),
    ]
