# Generated by Django 5.0.6 on 2024-06-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_alter_artwork_opening_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='opening_bid',
            field=models.IntegerField(default=0),
        ),
    ]
