# Generated by Django 5.0.6 on 2024-06-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_alter_artwork_opening_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
    ]
