# Generated by Django 5.0.6 on 2024-06-20 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_notification_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content',
        ),
    ]
