# Generated by Django 5.0.6 on 2024-06-20 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_remove_notification_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
