# Generated by Django 5.0.6 on 2024-07-01 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_notification_is_read_alter_notification_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
