# Generated by Django 5.0.6 on 2024-07-02 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_read',
            new_name='read',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
