# Generated by Django 5.0.6 on 2024-07-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='query',
            name='last_name',
        ),
    ]
