# Generated by Django 5.0.6 on 2024-07-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_alter_artwork_created_date_alter_artwork_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='created_date',
            field=models.DateField(),
        ),
    ]
