# Generated by Django 5.0.6 on 2024-07-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_alter_artwork_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
