# Generated by Django 5.0.6 on 2024-07-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_artwork_is_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='is_sold',
            field=models.BooleanField(default=True),
        ),
    ]
