# Generated by Django 5.0.6 on 2024-07-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_alter_artwork_is_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
