# Generated by Django 5.0.6 on 2024-07-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_rename_created_date_artwork_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='is_sold',
            field=models.BooleanField(default=True),
        ),
    ]
