# Generated by Django 5.0.6 on 2024-07-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_alter_artwork_is_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
