# Generated by Django 5.1 on 2024-11-16 18:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('waiting_for_response', 'Waiting for Response'), ('unsold', 'Unsold')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
