# Generated by Django 5.1 on 2024-11-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_artwork_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='buyer_response',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('no_response', 'No Response')], default='no_response', max_length=11),
        ),
        migrations.AddField(
            model_name='artwork',
            name='response_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
