# Generated by Django 5.1 on 2024-11-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_artwork_buyer_response_artwork_response_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('waiting_for_response', 'Waiting for Response'), ('unsold', 'Unsold')], default='active', max_length=50),
        ),
    ]
