# Generated by Django 5.1 on 2024-11-21 11:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_alter_bid_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
