# Generated by Django 5.1 on 2024-11-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=10, null=True),
        ),
    ]
