# Generated by Django 5.1 on 2024-11-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_feedback_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='sale_type',
            field=models.CharField(choices=[('discount', 'Discount'), ('bidding', 'Bidding')], default='bidding', max_length=10),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='opening_bid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
