# Generated by Django 5.1 on 2024-12-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_artwork_discounted_price_artwork_sale_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
