# Generated by Django 5.1 on 2024-12-01 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0071_alter_artwork_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='product_cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.catalogue'),
        ),
    ]
