# Generated by Django 5.1 on 2024-12-01 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0074_alter_artwork_end_date_alter_artwork_product_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='product_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.catalogue'),
        ),
    ]
