# Generated by Django 5.1 on 2024-12-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0076_alter_artwork_end_date_alter_artwork_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='product_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
