# Generated by Django 5.1 on 2024-12-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0078_alter_artwork_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_auction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artwork',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='sale_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('auction', 'Auction')], default='auction', max_length=10),
        ),
    ]
