# Generated by Django 5.1 on 2024-12-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0079_artwork_is_auction_artwork_is_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='is_auction',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='is_sale',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
    ]
