# Generated by Django 5.1 on 2024-12-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0080_remove_artwork_is_auction_remove_artwork_is_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='sale_type',
            field=models.CharField(choices=[('discount', 'Discount'), ('auction', 'Auction')], default='auction', max_length=10),
        ),
    ]
