# Generated by Django 5.1 on 2024-12-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0081_alter_artwork_sale_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='sale_type',
            field=models.CharField(choices=[('discount', 'Discount'), ('auction', 'Auction')], max_length=10),
        ),
    ]
