# Generated by Django 5.1 on 2024-12-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0082_alter_artwork_sale_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
