# Generated by Django 5.1 on 2024-12-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0083_alter_artwork_created_at_alter_artwork_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='response_deadline',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
