# Generated by Django 5.1 on 2024-12-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0084_alter_artwork_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
