# Generated by Django 5.1 on 2025-01-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0086_alter_feedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='source',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend')], default='frontend', max_length=10),
        ),
    ]
