# Generated by Django 5.1 on 2025-01-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0090_alter_artwork_sale_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='sale_type',
            field=models.CharField(choices=[('discount', 'Discount'), ('auction', 'Auction')], default='auction', max_length=50),
        ),
    ]
