# Generated by Django 5.1 on 2025-02-06 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0092_purchasecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='purchase_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.purchasecategory'),
        ),
    ]
