# Generated by Django 5.1 on 2025-02-07 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0093_artwork_purchase_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_artworks', to=settings.AUTH_USER_MODEL),
        ),
    ]
