# Generated by Django 5.1 on 2025-02-08 18:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0095_favoriteartwork'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteArtwork',
            new_name='Favorite',
        ),
    ]
