# Generated by Django 5.1.6 on 2025-02-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0096_rename_favoriteartwork_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='dimension_unit',
            field=models.CharField(choices=[('cm', 'Centimeters'), ('ft', 'Feet')], max_length=10),
        ),
    ]
