# Generated by Django 5.1.6 on 2025-02-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0097_alter_artwork_dimension_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='model_360',
            field=models.FileField(blank=True, null=True, upload_to='3d_models/'),
        ),
    ]
