# Generated by Django 5.1.6 on 2025-02-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0098_artwork_model_360'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='enable_ar',
            field=models.BooleanField(default=False),
        ),
    ]
