# Generated by Django 5.1.6 on 2025-02-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0099_artwork_enable_ar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='enable_ar',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
