# Generated by Django 5.1.6 on 2025-02-19 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0103_alter_artwork_enable_ar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='enable_ar',
        ),
    ]
