# Generated by Django 5.1.6 on 2025-02-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0105_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='refunded_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
