# Generated by Django 5.1.6 on 2025-03-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0106_alter_refund_refunded_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='product_id',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='product_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='product_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='product_qty',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
